package projects;

import java.util.Random;

import java.util.Scanner;

public class GuessRandomNumber {

	static Scanner sc = new Scanner(System.in);

	public static void main(String[] args) {
		System.out.println(
				"This is a simple game where you will have to guess the random number generated by the program.");
		System.out.println("You have only 3 chances to guess the number.");
		System.out.println("The number will be generated in the range of 0 to 10.");
		System.out.println("No clues! Only luck and raw guessing...");
		System.out.println("\nLet's play!!");
		System.out.println();
		String choice;
		do {
			guessRandom();
			System.out.println("----------------------------------------------------------");
			System.out.println("Do you want to play again?(y for yes/ n for no)");
			choice = sc.next();

		} while (choice.equalsIgnoreCase("y"));
		System.out.println("\nThanks for playing! 👋");
	}

	static void guessRandom() {
		Random r = new Random();
		int random_number = r.nextInt(11); // generates a integer in the range of 0 to 10

		System.out.println();
		int chances = 3;
		while (chances > 0) {
			System.out.print("Guess a number between 0 and 10 : ");
			int guess = sc.nextInt();

			if (guess < 0 || guess > 10) {
				System.out.println("Please enter a number between 0 and 10 only.\n");
				continue;
			}

			if (guess == random_number) {
				System.out.println("Congratulations! You win! 🎊");
				break;
			} else {
				chances--;
				System.out.println("❌ Wrong guess");
				System.out.println("You have " + chances + " chances left\n");
			}

			if (chances == 0) {
//				Thread.sleep(1000);
				System.out.println("The correct number was " + random_number);
			}
		}

	}

}
